name: Update Labels Across All Repos in Org

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml   

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up GitHub Token for API Authentication
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yq && sudo snap install yq

      - name: Get all repos in the organization and update their labels
        env:
          LABELS_PAT: ${{ secrets.LABELS_PAT }}
        id: get_repos
        run: |
          ORGANIZATION="queens-autodrive"
          RESPONSE=$(curl -s \
            -H "Authorization: token $LABELS_PAT" \
            "https://api.github.com/orgs/$ORGANIZATION/repos?per_page=100")
          REPOS=$(echo "$RESPONSE" | jq -r '.[].name')
          echo "REPOS=$REPOS" >> $GITHUB_ENV
          LABELS=$(cat .github/labels.yml)  
          echo $REPOS
          echo "$REPOS" | while IFS= read -r REPO; do
            echo "Updating labels in $REPO"
            echo "$LABELS" | yq e 'to_entries | .[] | "\(.key): color: \(.value.color), description: \(.value.description)"' - | while IFS= read -r label; do
              LABEL_NAME=$(echo "$label" | awk -F": color" '{print $1}' | xargs | tr -d '\n')
              LABEL_COLOR=$(echo "$label" | awk -F"color: " '{print $2}' | awk -F", description" '{print $1}' | xargs | tr -d '\n')
              LABEL_DESCRIPTION=$(echo "$label" | awk -F"description: " '{print $2}' | xargs | tr -d '\n')
              curl -X POST \
              -H "Authorization: token $LABELS_PAT" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"name": "'"$LABEL_NAME"'", "color": "'"$LABEL_COLOR"'", "description": "'"$LABEL_DESCRIPTION"'"}' \
              "https://api.github.com/repos/$ORGANIZATION/$REPO/labels"
            done
          done
